### ISSUE TITLE
withdraw() 

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#11]
- if(participantRecord.whitelisted == true) : using require() will make the code cleaner (currently it reverts at the end of the function). 
(https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L705)

- if(remainingTokenAmount > 0), maybe we should return instead: `if`  (remainingTokenAmount == 0) `to` make it more explicit.
( https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L723)

- assign  getCurrentStage() in the loop (https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L735)

- possible duplicate line participantRecord.withdrawnETH += returnETHAmount;
lines 794, 803

**Comment by mickys** [comment]
#1 - ok, require can work
#2 - ok
#3 - if done in the for() it will remove a stack item, that's cool.
#4 - yes, bad merge on my part.

**Comment by frozeman** [comment]
please make a PR
