### ISSUE TITLE
Use safeMath

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#12]
in some cases safe add or sub is not used because it is assumed that it is impossible to have an overflow, but it is best practice to use it in unclear cases just to avoid nasty surprises.

**Comment by mickys** [comment]
Need to upgrade to the latest safemath in order to support structs.

getStageAtBlock should not use it at [Line-567](https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L567)

**Comment by frozeman** [comment]
Please do that
