### ISSUE TITLE
cancel(), canCancelByEth() & cancelContributionsForAddress()

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#13]
- `if(canCancelByEth(msg.sender)) ...revert` can be turned into require for code clarity.

- canCancelByEth name is a bit confusing.

cancelContributionsForAddress():
- returnedETH += participantAvailableETH;  remove duplicate 
(https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L946)

- uint8 currentTransferEventType;  unnecessary complexity, use _eventType instead.
(https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L952)

- address(uint160(_from)).transfer(participantAvailableETH + msg.value);  sending back msg.value is a bit confusing since it is not payable, this is happening because the user can call  cancelContributionsForAddress() indirectly through fallback() but it can be also called through whitelist() from the whitelist controller. I think this is bad design/semantics.

**Comment by frozeman** [comment]
> if(canCancelByEth(msg.sender)) ...revert can be turned into require for code clarity.

agreed (for reference: https://github.com/lukso-network/rICO-smart-contracts/blob/develop/contracts/ReversibleICO.sol#L309)

> `canCancelByEth` name is a bit confusing.

I agree. I am not happy with those names. I also think we can simply merge that into one function like `hasPendingEth(address)`

And then we can rename `canCancelByTokens(address)` to `canWithdrawWithTokens(address)` or `userCanWithdraw(address)`

- I would also suggest renaming all `participant` naming to `user`. Makes it more simple. Please give feedback on that. Maybe participant is fine, as it is more concrete. Not sure.

> returnedETH += participantAvailableETH; remove duplicate

That looks like a bug @mickys as it is twice in the function. Currently is only used for the website metrics, not anything critical, luckily.
- [ ] Please fix.

> uint8 currentTransferEventType; unnecessary complexity, use _eventType instead.

I think they have different numbers `ApplicationEventTypes.WHITELIST_REJECT` and `TransferTypes.WHITELIST_REJECT`

> address(uint160(_from)).transfer(participantAvailableETH + msg.value)

I agree, I think it makes sense to add this as a parameter that is passed down
- [ ] please fix

**Comment by jenil04** [comment]
-> For `if(canCancelByEth(msg.sender)) ...revert` do we need the `cancelContributionsForAddress` function call if we set this requirement?:
```
require(canCancelByEth(msg.sender) == true)
```
I second on naming participant -> user.

**Comment by frozeman** [comment]
I changed `canCancelByEth ` to `hasPendingEth ` in moved the whitelist check into the function.

And made a `msg.value` as a function parameter as well.

Please see #4a8ca6d for more

**Comment by i-stam** [comment]
Addressed in #36
