### ISSUE TITLE
Internal functions should be turned into private

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#14]
If the rICO contract is not to be inherited then most if the internal functions should be turned into private. This will also eliminate the need of double modifier checking e.g. `isInitialized, isNotFrozen` in  commit() which is only called by fallback().

**Comment by frozeman** [comment]
good catch, but what if later anyone wants to create a modified rICO, where it allows for receiving tokens instead of ETH, then inheriting and calling commit from a `tokenReceived` function would be thinkable.

**Comment by frozeman** [comment]
for inheritance reasons i  wouldn't make them private.
