### ISSUE TITLE
projectWithdraw() & getProjectAvailableEth()

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#15]
**getProjectAvailableEth():**

- return var may not be needed (`returns (uint256 _amount)`)

- `projectAllocatedETH.sub(projectWithdrawnETH);` safeSub not needed in this case since it is checked in the if statement 
(https://github.com/lukso-network/rICO-smart-contracts/blob/master/contracts/ReversibleICO.sol#L347)

```
uint256 globalAvailable = acceptedETH
.sub(withdrawnETH)
.sub(projectWithdrawnETH)
.sub(remainingFromAllocation);
``` 
there is space for optimization: 
```
rem = pAllocated - pWithdrawn;
global = accepted - withdrawn  - pWithdrawn - rem =>
=> global = accepted - withdrawn  - pAllocated 
```
let's pick the one that makes the code more readable!

**Comment by frozeman** [comment]
For reference, here is the code
```
    function getProjectAvailableEth() public view returns (uint256 _amount) {

        uint256 remainingFromAllocation = 0;
        if(projectAllocatedETH > projectWithdrawnETH) {
            remainingFromAllocation = projectAllocatedETH.sub(projectWithdrawnETH);
        }

        // calculate ETH that is globally available
        uint256 globalAvailable = acceptedETH
            .sub(withdrawnETH)
            .sub(projectWithdrawnETH)
            .sub(remainingFromAllocation);

        // multiply the available ETH with the percentage that belongs to the project now
        uint256 unlocked = globalAvailable.mul(
            getCurrentUnlockPercentage()
        ).div(10 ** 20);

        return unlocked.add(remainingFromAllocation);
    }
```

**Comment by frozeman** [comment]
> return var may not be needed (returns (uint256 _amount))
you mean the naming or returning anything?
The return value is used here: https://github.com/lukso-network/rICO-smart-contracts/blob/develop/contracts/ReversibleICO.sol#L325

> projectAllocatedETH.sub(projectWithdrawnETH);

Good catch, still makes sense to use safe subtraction.

Could you make your optimisation more readable in your last point? I don't fully understand it.

**Comment by jenil04** [comment]
Ideally, it's safer to use .sub, .mul, .add over default operators to prevent overflows and readability.

**Comment by frozeman** [comment]
Please elaborate on the math improvements @i-stam.
