### ISSUE TITLE
whitelist() should be merged with whitelistMultiple()

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#16]
- there is no point in having 2 (it is also confusing  since whitelistMultiple() is public with no modifiers and  accessibility is enforced by calling whitelist() internally.

- for( uint16 i = 0; i < _address.length; i++ )  better to use uint256 instead of uint16.

**Comment by i-stam** [comment]
Additionally,  whitelistMultiple(address[] memory _address, bool _approve) can either approve or reject but not have a mixed list since _approve is not a list.

**Comment by frozeman** [comment]
merging makes sense. please make a PR.

I think only approving to rejecting is fine, mixed would make it more complicated also from a dev perspective. Its easier to call the function with a set of approved and then a set of rejected.

**Comment by i-stam** [comment]
Addressed in #33.
