### ISSUE TITLE
Extra storage allocated for commit phase not needed!

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#21]
Leads to duplicate statements.
e.g. `commitPhaseEndBlock = _commitPhaseStartBlock + _commitPhaseBlockCount;`
          and 
        `stage0.endBlock = _commitPhaseStartBlock + _commitPhaseBlockCount;`

We can use a getter for exposing the commit phase stats. e.g.
function commitPhaseEndBlock() external view returns (uint256){
  return stage0.endBlock;
}

**Comment by frozeman** [comment]
please make a PR.

**Comment by mickys** [comment]
commitPhaseEndBlock is used in getStageAtBlock, which in turn is used in more places.
cannot make that external, nor should it be a function as that would require calls which increase gas usage.

Also it's specifically there to allow the deployer to create more than 1 commit phase stage if they want to.
