### ISSUE TITLE
commit() refactoring

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#22]
- make it private, remove modifiers.

- `participantsById[participantCount] = msg.sender;` always skips 0 slot , could be fixed with
`participantsById[participantCount++] = msg.sender;`  perhaps.

- `msg.sender` is better if it becomes a parameter instead.

**Comment by mickys** [comment]
variable[var++] = something is harder for non technical people to understand, 
most will assume the var++ operation happens before variable[x] lookup, which is not the case.

**Comment by frozeman** [comment]
I agree with @mickys here. `var++` is not easy to understand that it increases after it was used.

The msg.sender should be a parameter, i agree. please make a PR.
as commitments are happening through sending ETH, an exposed custom function is not necessary. 

Removing the modifiers, when its internal would work, except the `notFrozen` one

**Comment by i-stam** [comment]
Addressed in #32
