### ISSUE TITLE
acceptContributionsForAddress() refactoring

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#23]
- `for (uint8 i = 0; i <= currentStage; i++) ` it is better to use a bigger uint since the rICO contract can be used in the future  for different scenarios requiring multiple stages.

- use safeMath e.g. `uint256 processedTotals = participantRecord.acceptedETH + participantRecord.returnedETH;`

- `bytes memory data;` can be  hardcoded as a function parameter.

**Comment by frozeman** [comment]
for uint, is the gas cost higher when we use `unit16` for example?

Other wise please make a PR for all the other issues, i agree with all of them.

**Comment by mickys** [comment]
The EVM works with 256bit/32byte words, so using anything smaller than uint256 does add extra operations which use up some gas. 
Slightly higher gas cost is true for code execution in memory, yet a lot cheaper for storage.

Do however keep in mind to update getStageAtBlock to reflect the change if you update to uint16.

**Comment by i-stam** [comment]
Additionally, I think it would that the  `if (processedTotals < participantRecord.totalReceivedETH) {` should be moved outside of the loop, after the end of the loop there should be a `require` for checking if everything is consistent i.e. `processedTotals == participantRecord.totalReceivedETH`
