### ISSUE TITLE
Token price increases on a per stage basis

### ISSUE THREAD

**Issue by i-stam** [lukso-network/rICO-smart-contracts#25]
```
Since our tokens cost less than 1 eth, and decimals are 18
1 wei will always buy something.
```
Not sure if this is always true especially if we want to generalize the rICO contract.

**Comment by frozeman** [comment]
We could add decimals setting, but as of now most tokens agreed to use 18 decimals, as a default.

Maybe it makes sense to set the token price in amounts of tokens that can be bought for 1 WEI.
This way we avoid floating numbers when calculating.
